### ISSUE TITLE
CI 測試

### ISSUE THREAD

**Issue by abc873693** [NKUST-ITC/NKUST-AP-Flutter#109]
## CI 工具選用
- GitHub Action

## 測試項目
- 編譯測試
  - [x] Android
  - [x] iOS
  - [x] Web
  - [x] macOS
  - [x] Linux
  - [x] Windows
- 單元測試
  - [x] Model Test Stage 1

**Comment by vn7n24fzkq** [comment]
Hi, @abc873693 .
What Does TBD Mean?
"to be determined" or "to be done" or "to be deleted" or "to be decided" ?

**Comment by abc873693** [comment]
> Hi, @abc873693 .
> What does TBD mean?
> "to be determined" or "to be done" or "to be deleted" or "to be decided" ?

To Be Discussed

**Comment by vn7n24fzkq** [comment]
Thanks! :)

**Comment by abc873693** [comment]
主要核心功能集中於 `ap_common`
另外至此追蹤 https://github.com/abc873693/ap_common/issues/40
