### ISSUE TITLE
apHelper & busHelper 重新嘗試過多次

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#122]
* busHelper中重新嘗試的`isLogin`沒有判斷`null`
* apHelper `apQuery`應該要包含判斷`isLogin`
* 移除部分Helper與 busHelper和apHelper 功能重複的地方

* 回到HomePage應該要恢復busHelper的重試次數

**Comment by abc873693** [comment]
第四點的原因？
PR本身是處理四個問題？
