### ISSUE TITLE
Dio 未實作Transfer-Encoding造成資料不乾淨

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#132]
如題
已知在爬取課表/教室課表時
在data中會有異常的雜訊在表頭及內文穿插
使用Proxy以及使用Curl 並沒有發現有異常的地方

異常雜訊
<img width="227" alt="截圖 2020-08-22 下午7 49 41" src="https://user-images.githubusercontent.com/37475932/90958175-3cebd480-e4c5-11ea-9476-4f5ebd0b26ec.png">
<img width="392" alt="截圖 2020-08-22 下午7 49 35" src="https://user-images.githubusercontent.com/37475932/90958177-4412e280-e4c5-11ea-9be0-fc7f1da2e228.png">

**Comment by abc873693** [comment]
@takidog  目前的版本是已經處理完畢？
還是會有些例外？

**Comment by takidog** [comment]
會有例外
剛好切掉中文字

從教室課表看來，應該是很少發生
