### ISSUE TITLE
行事曆讀取失敗

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#140]
`Version: 3.4.7`

![photo_2020-08-27 01 12 59](https://user-images.githubusercontent.com/37475932/91335142-94aa7880-e802-11ea-8626-a126772bf9be.jpeg)

**Comment by abc873693** [comment]
Fix in 3174980830a18237efb4382d12d727ec95945e63
ap_common v0.5.3 加入pdf狀態管理
