### ISSUE TITLE
虛擬閱覽證

### ISSUE THREAD

**Issue by ghost** [NKUST-ITC/NKUST-AP-Flutter#149]

**Comment by vn7n24fzkq** [comment]
J個 issue 是....？

**Comment by waazxc77548** [comment]
算是吧
不過我等會會把自己寫的版本上傳

**Comment by abc873693** [comment]
學校目前的 Qr Code 虛擬閱覽證是 Bar Code 或 Qr Code 
內容單純只有學號 
先前已在 a24c361494437f28f3c152474120993f3d02b929
約v3.3.14 實作完畢
需要確認學校是否有再修改？

**Comment by waazxc77548** [comment]
自己截圖用掃描器檢查了虛擬閱覽證的Qr Code和Bar Code確定只有學號
近期會參考樓上講的功能範例修改

**Comment by abc873693** [comment]
> 自己截圖用掃描器檢查了虛擬閱覽證的Qr Code和Bar Code確定只有學號
> 近期會參考樓上講的功能範例修改

確定與現行版本相同
這樣就不用實作了
已經實作出來了
![](https://i.imgur.com/AiaS1no.jpg)
