### ISSUE TITLE
校車預定/取消失敗，顯示錯誤

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#155]
應該是爬蟲問題
還有一個是顯示問題(?
顯示問題:
早上9點之前的校車，在前日下午就會禁止預定or取消
時刻表上沒有反灰

可能是爬蟲問題:
取消或是預定，是失敗但卻顯示成功

**Comment by abc873693** [comment]
Fix in 87f814556d92e10739b38353a991241a7b6dffdb
