### ISSUE TITLE
API服務透過遠端切換

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#158]
如題

是否要透過firebase
或是在firebase增加控制方式去選擇單一功能要使用哪一個系統的API?

例如:
現在`inkust`掛了，可以透過remote config 設定去選擇 `ap`  甚至 `aais 選課系統`

或是把semester移動到firebase上，在校方API有更動的時候，可以臨時關閉部分功能

增加更多彈性(?

**Comment by abc873693** [comment]
理論上 可以 但實際上要切多細

**Comment by takidog** [comment]
請假(缺曠與假單列表、請假申請)
課表
成績查詢
學期列表

防止未來`ap`增加reCAPTCH A影響到主要的功能

**Comment by abc873693** [comment]
登入 要怎麼拆

**Comment by takidog** [comment]
> 登入 要怎麼拆

哪個方面怎麼拆

切換登入的系統應該沒問題
從Helper讀到config去切換(？

**Comment by abc873693** [comment]
就是ap的登入和inkust的登入

**Comment by takidog** [comment]
> 就是ap的登入和inkust的登入

沒什麼問題吧，我之後再試看看

**Comment by abc873693** [comment]
875f7297e4c3fc2a3713a51789ca8fd1f50c3d95
dfb62c386b0fec600a8faa000dcb275a55147816
90e15afb9be8ac1c8ad8b545a9b46590c029ec0b
ac7b9d57e557d3db13e9508846b93fc71694dff7

透過 `Firebase Remote Config` 控制 Crawler Selector

現行版本支援
 - course
 - score
 - login
 - user info
 - semester
