### ISSUE TITLE
串接mobile.nkust取代inkust 

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-Flutter#170]
as title

inkust 在2021/02 有關閉的公告
要替換目前的功能到mobile.nkust
`https://mobile.nkust.edu.tw/`

------------------------------------
目前進度
 - [x] 登入
 - [x] 課表
 - [x] 成績
 - [x] 校車
 - [x] 缺曠
 - [x] 期中預警

**Comment by abc873693** [comment]
目前進度
 - [ ] 登入
 - [ ] 課表
 - [ ] 成績
 - [ ] 校車
 - [ ] 缺曠
 - [ ] 期中預警

**Comment by takidog** [comment]
目前(3.6)  串接的狀態
登入  `webap`
課表 `inkust`
成績 `webap`
學期列表 `webap`
期中預警 `webap`
校車 `inkust`
請假/缺曠 `inkust`

**Comment by abc873693** [comment]
缺曠系統 暫時使用 `WebView` 取代
缺曠爬蟲另開 https://github.com/NKUST-ITC/NKUST-AP-Flutter/issues/185 追蹤
