### ISSUE TITLE
校務系統要求更改密碼

### ISSUE THREAD

**Issue by mlgzackfly** [NKUST-ITC/NKUST-AP-Flutter#212]
現在每90天校務系統會要求更改密碼
登入後連線至 `https://webap.nkust.edu.tw/nkust/system/sys010_stay.jsp` 可以沿用舊密碼

**Comment by abc873693** [comment]
有辦法判斷此狀況?

**Comment by mlgzackfly** [comment]
要求使用者改的話是不是還需要一個更改密碼的頁面（？

**Comment by takidog** [comment]
對的，但應該就只有，密碼、確認密碼
然後更新儲存的密碼

吧
