### ISSUE TITLE
Android 12 課程提醒無法顯示

### ISSUE THREAD

**Issue by TreeHD** [NKUST-ITC/NKUST-AP-Flutter#213]
剛更新上Android 12
桌面小工具的課程顯示沒有東西

在Android 11時可以正常使用
![Screenshot_20220322-103002_Pixel Launcher](https://user-images.githubusercontent.com/23317010/159396226-01518388-d5af-46f8-86c6-50ed8b67221b.png)

**Comment by abc873693** [comment]
69d10787f9afd480207a51739f30e2f038ffa1e2
