### ISSUE TITLE
無法登入，持續顯示「沒有網路連線，請檢查你的網路」

### ISSUE THREAD

**Issue by wasd52030** [NKUST-ITC/NKUST-AP-Flutter#215]
如標題，最近使用時一直顯示「沒有網路連線，請檢查你的網路」，不管是開了行動網路或是Wi-Fi都一樣

型號: Sony Xperia 10 III
系統: Android 12

**Comment by abc873693** [comment]
Fix in a6303b202d3015bc9e1117e787cb7be96e6e1e6e
