### ISSUE TITLE
Improve course layout

### ISSUE THREAD

**Issue by hearsilent** [NKUST-ITC/NKUST-AP-Flutter#46]

**Comment by abc873693** [comment]
#14

**Comment by abc873693** [comment]
Finish by #77

**Comment by AlexVincent525** [comment]
Great job what you guys have done! We have done a pretty layout using nothing but only flex widgets in [course schedule page](https://github.com/openjmu/OpenJMU/blob/master/lib/pages/home/course_schedule_page.dart) and hope this helps. 😺 (See screenshot)

Other than that, it's good for us to see a student group (same as us) which is working on Flutter too. 👍 

![](https://camo.githubusercontent.com/addbe3bcbbb0b14db70bcd85c842d1c878481997/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30322f31382f4f446873416d756b786e4e7958334d2e6a7067)

**Comment by abc873693** [comment]
> Great job what you guys have done! We have done a pretty layout using nothing but only flex widgets in [course schedule page](https://github.com/openjmu/OpenJMU/blob/master/lib/pages/home/course_schedule_page.dart) and hope this helps. 😺 (See screenshot)
> 
> Other than that, it's good for us to see a student group (same as us) which is working on Flutter too. 👍
> 
> ![](https://camo.githubusercontent.com/addbe3bcbbb0b14db70bcd85c842d1c878481997/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30322f31382f4f446873416d756b786e4e7958334d2e6a7067)

We create this [package](https://github.com/abc873693/ap_common) for improve UI logic.
Update course page UI in v3.4.0.
![](https://raw.githubusercontent.com/abc873693/ap_common/master/images/course_scaffold/tablet.png)
