### ISSUE TITLE
Bus rule English version

### ISSUE THREAD

**Issue by abc873693** [NKUST-ITC/NKUST-AP-Flutter#66]

**Comment by abc873693** [comment]
@mick3773 Have any progress?

**Comment by junk87** [comment]
I pull request now, sorry for long time waiting.

> @mick3773 Have any progress?

**Comment by abc873693** [comment]
WIP in https://github.com/NKUST-ITC/NKUST-AP-Flutter/tree/feture/bus-rule-english-version

**Comment by abc873693** [comment]
Finish in https://github.com/NKUST-ITC/NKUST-AP-Flutter/pull/111
