### ISSUE TITLE
Add bus_rule_page to app_localizations

### ISSUE THREAD

**Issue by mick3773** [NKUST-ITC/NKUST-AP-Flutter#84]
Could you change lib/pages/home/bus/bus_rule_page.dart add to lib/utils/app/app_localizations.dart?
I wanna help to translate bus rule(#66 ).

Thanks.

**Comment by abc873693** [comment]
Yes, update `app_localizations.dart` and `bus_rule_page.dart`

**Comment by abc873693** [comment]
Only comment in #66
